### ISSUE TITLE
Allow for port 8883 due to slightly different setup

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_CircuitPython_FunHouse#4]
From @brentru:
```
return self.init_mqtt(IO_MQTT_BROKER, 1883, aio_username, aio_key, True)
```
Users may want to use secure port 8883. Setting up the client for the S2/SSL will be different and may need to be modified.

**Comment by makermelissa** [comment]
@brentru, do you have any examples for what is different?

**Comment by brentru** [comment]
Yes, please see the example for ESP32-S2 here: https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/master/examples/minimqtt_simpletest.py

Check out both the `import`s, and L75 through L86. MiniMQTT defaults to the secure port `8883`, we should support that in this library by default.
